// <auto-generated />
using System;
using BrainX.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrainX.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BrainX.Api.Data.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudySessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BrainX.Api.Data.StudyMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("BrainX.Api.Data.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BrainX.Api.Data.TutorKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keyword = "variavel",
                            Response = "Em C#, variáveis são espaços de memória reservados. Exemplo: 'int idade = 25;' declara uma variável inteira.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Keyword = "poo",
                            Response = "POO (Programação Orientada a Objetos) baseia-se em Classes e Objetos. Seus 4 pilares são: Herança, Polimorfismo, Encapsulamento e Abstração.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Keyword = "tipos de dados",
                            Response = "Tipos primitivos em C#: int (inteiros), double/decimal (decimais), string (texto) e bool (verdadeiro/falso).",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Keyword = "herança",
                            Response = "Herança permite que uma classe herde características de outra. Usamos os dois pontos (:). Ex: public class Cachorro : Animal { }",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 5,
                            Keyword = "polimorfismo",
                            Response = "Polimorfismo significa 'muitas formas'. Permite sobrescrever métodos da classe pai usando as palavras 'virtual' e 'override'.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 6,
                            Keyword = "encapsulamento",
                            Response = "Encapsulamento é proteger os dados de uma classe. Usamos modificadores como 'private' e expomos os dados através de Propriedades (get e set).",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 7,
                            Keyword = "interface",
                            Response = "Uma Interface é um contrato. Ela define QUAIS métodos uma classe deve ter, mas não COMO eles funcionam. Usamos 'interface IExemplo'.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 8,
                            Keyword = "classe abstrata",
                            Response = "Uma classe abstrata (abstract class) não pode ser instanciada diretamente, serve apenas como base (molde) para outras classes herdarem.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 9,
                            Keyword = "for",
                            Response = "O laço 'for' é usado quando sabemos o número exato de repetições. Exemplo: for(int i=0; i<10; i++) { ... }",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 10,
                            Keyword = "while",
                            Response = "O laço 'while' repete um bloco enquanto uma condição for verdadeira. Cuidado para não criar loops infinitos!",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 11,
                            Keyword = "foreach",
                            Response = "O 'foreach' é ideal para percorrer listas e arrays. Ex: foreach(var item in lista) { Console.WriteLine(item); }",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 12,
                            Keyword = "try catch",
                            Response = "O bloco 'try-catch' trata erros. O código que pode quebrar vai no 'try', e a solução ou mensagem de erro vai no 'catch'.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 13,
                            Keyword = "array",
                            Response = "Arrays são coleções de tamanho FIXO. Ex: int[] numeros = new int[5]; cria um array para 5 números.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 14,
                            Keyword = "lista",
                            Response = "Listas (List<T>) são coleções DINÂMICAS. Você pode adicionar com .Add() e remover com .Remove() sem se preocupar com o tamanho limite.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 15,
                            Keyword = "linq",
                            Response = "LINQ é uma linguagem de consulta integrada. Permite filtrar listas facilmente, ex: var filtrado = lista.Where(x => x.Idade > 18).ToList();",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 16,
                            Keyword = "async await",
                            Response = "O 'async/await' é usado para programação assíncrona. Ele permite que o programa continue rodando enquanto espera o banco de dados responder, por exemplo.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 17,
                            Keyword = "entity framework",
                            Response = "O Entity Framework (EF Core) é um ORM. Ele traduz seu código C# para comandos SQL automaticamente, facilitando o acesso ao banco de dados.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 18,
                            Keyword = "api",
                            Response = "API (Application Programming Interface) é uma ponte de comunicação. No .NET, criamos APIs REST usando Controllers para retornar dados em JSON.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 19,
                            Keyword = "json",
                            Response = "JSON é o formato padrão de troca de dados na web. Em C#, usamos System.Text.Json para transformar objetos em texto e vice-versa (Serialização).",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 20,
                            Keyword = "injecao de dependencia",
                            Response = "Injeção de Dependência (DI) é um padrão onde o sistema fornece os objetos que uma classe precisa para funcionar. No .NET, configuramos isso no builder.Services.",
                            Subject = "C#"
                        },
                        new
                        {
                            Id = 21,
                            Keyword = "pitagoras",
                            Response = "Em um triângulo retângulo, a soma dos quadrados dos catetos é igual ao quadrado da hipotenusa (a² = b² + c²).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 22,
                            Keyword = "bhaskara",
                            Response = "A Fórmula de Bhaskara acha raízes da equação do 2º grau: x = (-b ± √Δ) / 2a.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 23,
                            Keyword = "delta",
                            Response = "O Delta (Δ) é Δ = b² - 4ac. Δ > 0: duas raízes. Δ = 0: uma raiz. Δ < 0: sem raízes reais.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 24,
                            Keyword = "fracao",
                            Response = "Fração tem numerador (parte de cima) e denominador (parte de baixo). Para somar denominadores diferentes, faça o MMC.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 25,
                            Keyword = "porcentagem",
                            Response = "Porcentagem é uma razão de base 100. 20% de 50 = (20/100) * 50 = 10.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 26,
                            Keyword = "regra de tres",
                            Response = "Regra de três simples resolve problemas proporcionais. Multiplica-se cruzado quando são diretamente proporcionais.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 27,
                            Keyword = "juros simples",
                            Response = "Fórmula do Juros Simples: J = C * i * t (Capital x Taxa x Tempo).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 28,
                            Keyword = "juros compostos",
                            Response = "Fórmula do Juros Compostos: M = C * (1 + i)^t (O famoso 'juros sobre juros').",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 29,
                            Keyword = "logaritmo",
                            Response = "Logaritmo: log_b(a) = x significa que b^x = a. A 'Regra do Tombo' é: log(a^b) = b * log(a).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 30,
                            Keyword = "trigonometria",
                            Response = "No triângulo retângulo (SOH CAH TOA): Seno (Oposto/Hipotenusa), Cosseno (Adjacente/Hipotenusa), Tangente (Oposto/Adjacente).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 31,
                            Keyword = "probabilidade",
                            Response = "Probabilidade = (Casos Favoráveis) / (Casos Possíveis). A chance de tirar o número 4 num dado é 1/6.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 32,
                            Keyword = "media",
                            Response = "Média Aritmética: soma tudo e divide pela quantidade de itens. (Ex: notas 6 e 8 = 14/2 = Média 7).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 33,
                            Keyword = "mediana",
                            Response = "Mediana é o número do meio em uma lista organizada em ordem crescente. Se for par, faz a média dos dois centrais.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 34,
                            Keyword = "moda",
                            Response = "Moda, na estatística, é o valor que mais se repete em um conjunto de dados.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 35,
                            Keyword = "fatorial",
                            Response = "Fatorial (n!) é a multiplicação de um número pelos seus antecessores. Ex: 4! = 4 x 3 x 2 x 1 = 24.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 36,
                            Keyword = "permutacao",
                            Response = "Permutação (Pn = n!) é a forma de organizar todos os elementos de um conjunto em ordem. Quantos anagramas tem a palavra AMOR? 4! = 24.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 37,
                            Keyword = "arranjo",
                            Response = "No Arranjo, a ordem dos elementos IMPORTA (ex: senhas, pódio). Fórmula: A(n,p) = n! / (n-p)!",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 38,
                            Keyword = "combinacao",
                            Response = "Na Combinação, a ordem NÃO importa (ex: montar um grupo, salada de frutas). Fórmula: C(n,p) = n! / [p! * (n-p)!]",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 39,
                            Keyword = "matriz",
                            Response = "Matrizes são tabelas de números organizados em Linhas x Colunas. Usadas para resolver sistemas lineares complexos.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 40,
                            Keyword = "funcao do primeiro grau",
                            Response = "Função de 1º Grau (Afim): f(x) = ax + b. O gráfico é sempre uma Reta.",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 41,
                            Keyword = "funcao do segundo grau",
                            Response = "Função de 2º Grau (Quadrática): f(x) = ax² + bx + c. O gráfico é uma Parábola (curva em formato de U ou U invertido).",
                            Subject = "Matemática"
                        },
                        new
                        {
                            Id = 42,
                            Keyword = "crase",
                            Response = "A crase é a fusão da preposição 'a' com o artigo feminino 'a'. Nunca use antes de palavras masculinas ou verbos.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 43,
                            Keyword = "porque",
                            Response = "'Por que' (pergunta/motivo). 'Porque' (resposta). 'Por quê' (fim de frase). 'Porquê' (substantivo: 'o porquê').",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 44,
                            Keyword = "mas",
                            Response = "'Mas' é oposição (porém, contudo). Ex: Tentei, MAS não consegui.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 45,
                            Keyword = "mais",
                            Response = "'Mais' indica adição, intensidade, oposto de 'menos'. Ex: Quero MAIS café.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 46,
                            Keyword = "mal e mau",
                            Response = "'Mal' é o oposto de BEM (Ele canta mal). 'Mau' é o oposto de BOM (Ele é um lobo mau).",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 47,
                            Keyword = "onde e aonde",
                            Response = "'Onde' indica lugar fixo (Onde você mora?). 'Aonde' indica movimento (Aonde você vai?).",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 48,
                            Keyword = "senao",
                            Response = "'Senão' junto significa 'caso contrário' (Estude, senão vai reprovar). 'Se não' separado indica condição (Se não chover, eu vou).",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 49,
                            Keyword = "virgula",
                            Response = "Vírgula separa enumerações e isola vocativos. Regra de Ouro: NUNCA separe o Sujeito do Verbo com vírgula!",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 50,
                            Keyword = "sujeito",
                            Response = "Sujeito é quem sofre ou pratica a ação. Pode ser Simples, Composto (João e Maria), Oculto ou Indeterminado.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 51,
                            Keyword = "predicado",
                            Response = "Predicado é tudo aquilo que se declara sobre o sujeito. Ex: O cachorro (sujeito) 'mordeu o carteiro' (predicado).",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 52,
                            Keyword = "metafora",
                            Response = "Metáfora é uma comparação implícita. Ex: 'Seu coração é de gelo' (não usamos a palavra 'como').",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 53,
                            Keyword = "pleonasmo",
                            Response = "Pleonasmo é a repetição desnecessária de uma ideia. Exemplo clássico: 'Subir para cima' ou 'Entrar para dentro'.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 54,
                            Keyword = "hiperbole",
                            Response = "Hipérbole é o exagero intencional para dar ênfase. Ex: 'Estou morrendo de fome!' ou 'Já te falei um milhão de vezes!'.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 55,
                            Keyword = "eufemismo",
                            Response = "Eufemismo é suavizar uma expressão chocante ou triste. Ex: Em vez de 'morreu', dizer 'passou dessa para uma melhor'.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 56,
                            Keyword = "ironia",
                            Response = "Ironia é afirmar o contrário do que se pensa. Ex: 'Que garoto inteligente, zerou a prova!'.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 57,
                            Keyword = "paradoxo",
                            Response = "Paradoxo é unir ideias que se contradizem no mesmo contexto. Ex: 'Estou cego, mas agora consigo ver a verdade'.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 58,
                            Keyword = "proparoxitona",
                            Response = "Palavras proparoxítonas têm a antepenúltima sílaba tônica. Regra: TODAS as proparoxítonas são acentuadas. Ex: Má-gi-co, Lám-pa-da.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 59,
                            Keyword = "oxitona",
                            Response = "Oxítonas têm a última sílaba forte. Acentuam-se as terminadas em A, E, O, EM. Ex: Ca-fé, Ci-pó, Ar-ma-zém.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 60,
                            Keyword = "verbo",
                            Response = "Verbo indica Ação (correr), Estado (ser, estar) ou Fenômeno da Natureza (chover). Ele flexiona em tempo, modo, número e pessoa.",
                            Subject = "Português"
                        },
                        new
                        {
                            Id = 61,
                            Keyword = "adjetivo",
                            Response = "Adjetivo é a palavra que dá uma característica, qualidade ou estado ao Substantivo. Ex: Carro 'RÁPIDO', Menina 'INTELIGENTE'.",
                            Subject = "Português"
                        });
                });

            modelBuilder.Entity("BrainX.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrainX.Api.Data.ChatMessage", b =>
                {
                    b.HasOne("BrainX.Api.Data.StudySession", null)
                        .WithMany("Messages")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrainX.Api.Data.StudySession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
